blocks:
  - name: Step1
    step:
      integration: python
      python:
        body: |
          # Use Python to:
          #
          # 1. Transform the output of previous Steps by referencing their output (ex. Step1.output)
          # 2. Write logic referencing UI components (ex. Table1.selectedRow.id)
          # 3. Make http calls using requests (import requests)
          #
          # More libraries are coming in the future. Superblocks uses Python 3.

          return { "value": "Hello Superblocks!" }
metadata:
  description: ""
  folder: ""
  id: 4dbbf373-11d8-45e6-85f2-2cc5ba38906e
  name: API3
  organization: 2f6e8721-cf85-4bce-ba55-f735cc0ac3de
  tags: {}
  version: ""
trigger:
  application:
    id: 07b5eb5a-1383-414b-892d-987c3af70064
