blocks:
  - conditional:
      else:
        blocks: []
      elseIf:
        - blocks: []
          condition: "{{}}"
        - blocks: []
          condition: "{{}}"
      if:
        blocks: []
        condition: "{{2 > 1}}"
    name: Condition1
  - loop:
      blocks:
        - break:
            condition: "{{true}}"
          name: Break1
      range: "{{[1,2,3]}}"
      type: TYPE_FOREACH
      variables:
        index: index
        item: itemasdf
    name: Loop1
  - name: TryCatch1
    tryCatch:
      catch:
        blocks: []
      try:
        blocks: []
      variables:
        error: error
  - name: Send1
    send:
      message: '{{"Message data"}}'
  - name: Variables1
    variables:
      items:
        - key: myVar
          mode: MODE_READWRITE
          type: TYPE_SIMPLE
          value: '{{"my variable value"}}'
        - key: vaer2
          mode: MODE_READWRITE
          type: TYPE_SIMPLE
          value: '{{"my variable value"}}'
  - name: Parallel1
    parallel:
      poolSize: 20
      static:
        paths:
          Path1:
            blocks: []
          Path2:
            blocks: []
      wait: WAIT_NONE
  - name: Stream1
    stream:
      options:
        disableAutoSend: false
      variables:
        item: message
  - name: Return1
    return:
      data: '{{"Return data"}}'
  - name: ThrowError1
    throw:
      error: '{{"An error occurred"}}'
  - name: Wait1
    wait:
      condition: ""
metadata:
  description: ""
  folder: ""
  id: 17e7a796-7575-4214-b5f8-8696d0cc6aaa
  name: API5
  organization: 2f6e8721-cf85-4bce-ba55-f735cc0ac3de
  tags: {}
  version: ""
trigger:
  application:
    id: 07b5eb5a-1383-414b-892d-987c3af70064
