blocks:
  - conditional:
      else:
        blocks: []
      elseIf: []
      if:
        blocks: []
        condition: "{{2 > 1}}"
    name: Condition1
metadata:
  description: ""
  folder: ""
  id: 40f25eff-4770-4735-bb96-21833bbd3b52
  name: API6
  organization: 2f6e8721-cf85-4bce-ba55-f735cc0ac3de
  tags: {}
  version: ""
trigger:
  application:
    id: 07b5eb5a-1383-414b-892d-987c3af70064
